package br.com.fichasordens.entities;
// Generated 03/03/2018 14:18:32 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente", schema = "public")
public class ClienteEntity implements java.io.Serializable {
	private static final long serialVersionUID = 2945683658337030647L;
	
	private Long id;
	private EnderecoEntity endereco;
	private String nome;
	private String cnpjCpf;
	private String celular;
	private String fone;
	private String email;
	private Set<OrdemServicoEntity> ordemServicos = new HashSet<OrdemServicoEntity>(0);
	private Set<FichaAtendimento> fichaAtendimentos = new HashSet<FichaAtendimento>(0);

	public ClienteEntity() {
	}

	public ClienteEntity(Long id, EnderecoEntity endereco, String nome, String cnpjCpf, String celular) {
		this.id = id;
		this.endereco = endereco;
		this.nome = nome;
		this.cnpjCpf = cnpjCpf;
		this.celular = celular;
	}

	public ClienteEntity(Long id, EnderecoEntity endereco, String nome, String cnpjCpf, String celular, String fone,
			String email, Set<OrdemServicoEntity> ordemServicos, Set<FichaAtendimento> fichaAtendimentos) {
		this.id = id;
		this.endereco = endereco;
		this.nome = nome;
		this.cnpjCpf = cnpjCpf;
		this.celular = celular;
		this.fone = fone;
		this.email = email;
		this.ordemServicos = ordemServicos;
		this.fichaAtendimentos = fichaAtendimentos;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="cliente_sequencia")
	@SequenceGenerator(name="cliente_sequencia", sequenceName="cliente_sequencia", allocationSize=1)
	@Column(name = "id", unique = true, nullable = false, precision = 131089, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "endereco_id", nullable = false)
	public EnderecoEntity getEndereco() {
		return this.endereco;
	}

	public void setEndereco(EnderecoEntity endereco) {
		this.endereco = endereco;
	}

	@Column(name = "nome", nullable = false, length = 50)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "cnpj_cpf", nullable = false, length = 18)
	public String getCnpjCpf() {
		return this.cnpjCpf;
	}

	public void setCnpjCpf(String cnpjCpf) {
		this.cnpjCpf = cnpjCpf;
	}

	@Column(name = "celular", nullable = false, length = 15)
	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	@Column(name = "fone", length = 15)
	public String getFone() {
		return this.fone;
	}

	public void setFone(String fone) {
		this.fone = fone;
	}

	@Column(name = "email", length = 80)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<OrdemServicoEntity> getOrdemServicos() {
		return this.ordemServicos;
	}

	public void setOrdemServicos(Set<OrdemServicoEntity> ordemServicos) {
		this.ordemServicos = ordemServicos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<FichaAtendimento> getFichaAtendimentos() {
		return this.fichaAtendimentos;
	}

	public void setFichaAtendimentos(Set<FichaAtendimento> fichaAtendimentos) {
		this.fichaAtendimentos = fichaAtendimentos;
	}

}
