package br.com.fichasordens.entities;
// Generated 03/03/2018 14:18:32 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Empresa generated by hbm2java
 */
@Entity
@Table(name = "empresa", schema = "public")
public class EmpresaEntity implements java.io.Serializable {

	private long id;
	private EnderecoEntity endereco;
	private String nome;
	private String cnpj;
	private String fone;
	private String emai;
	private String site;

	public EmpresaEntity() {
	}

	public EmpresaEntity(long id, EnderecoEntity endereco, String nome, String cnpj, String fone, String emai, String site) {
		this.id = id;
		this.endereco = endereco;
		this.nome = nome;
		this.cnpj = cnpj;
		this.fone = fone;
		this.emai = emai;
		this.site = site;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "endereco_id", nullable = false)
	public EnderecoEntity getEndereco() {
		return this.endereco;
	}

	public void setEndereco(EnderecoEntity endereco) {
		this.endereco = endereco;
	}

	@Column(name = "nome", nullable = false, length = 50)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "cnpj", nullable = false, length = 18)
	public String getCnpj() {
		return this.cnpj;
	}

	public void setCnpj(String cnpj) {
		this.cnpj = cnpj;
	}

	@Column(name = "fone", nullable = false, length = 15)
	public String getFone() {
		return this.fone;
	}

	public void setFone(String fone) {
		this.fone = fone;
	}

	@Column(name = "emai", nullable = false, length = 80)
	public String getEmai() {
		return this.emai;
	}

	public void setEmai(String emai) {
		this.emai = emai;
	}

	@Column(name = "site", nullable = false, length = 80)
	public String getSite() {
		return this.site;
	}

	public void setSite(String site) {
		this.site = site;
	}

}
