package br.com.fichasordens.entities;
// Generated 03/03/2018 14:18:32 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Endereco generated by hbm2java
 */
@Entity
@Table(name = "endereco", schema = "public")
public class EnderecoEntity implements java.io.Serializable {

	private Long id;
	private String logradouro;
	private String bairro;
	private String cidade;
	private String estado;
	private int numero;
	private String cep;
	private String complemento;
	private Set<EmpresaEntity> empresas = new HashSet<EmpresaEntity>(0);
	private Set<ClienteEntity> clientes = new HashSet<ClienteEntity>(0);

	public EnderecoEntity() {
	}

	public EnderecoEntity(Long id, String logradouro, String bairro, String cidade, String estado, int numero) {
		this.id = id;
		this.logradouro = logradouro;
		this.bairro = bairro;
		this.cidade = cidade;
		this.estado = estado;
		this.numero = numero;
	}

	public EnderecoEntity(Long id, String logradouro, String bairro, String cidade, String estado, int numero,
			String cep, String complemento, Set<EmpresaEntity> empresas, Set<ClienteEntity> clientes) {
		this.id = id;
		this.logradouro = logradouro;
		this.bairro = bairro;
		this.cidade = cidade;
		this.estado = estado;
		this.numero = numero;
		this.cep = cep;
		this.complemento = complemento;
		this.empresas = empresas;
		this.clientes = clientes;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="endereco_sequencia")
	@SequenceGenerator(name="endereco_sequencia", sequenceName="endereco_sequencia", allocationSize=1)
	//@Column(name = "id", unique = true, nullable = false, precision = 131089, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "logradouro", nullable = false, length = 60)
	public String getLogradouro() {
		return this.logradouro;
	}

	public void setLogradouro(String logradouro) {
		this.logradouro = logradouro;
	}

	@Column(name = "bairro", nullable = false, length = 40)
	public String getBairro() {
		return this.bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	@Column(name = "cidade", nullable = false, length = 40)
	public String getCidade() {
		return this.cidade;
	}

	public void setCidade(String cidade) {
		this.cidade = cidade;
	}

	@Column(name = "estado", nullable = false, length = 25)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "numero", nullable = false)
	public int getNumero() {
		return this.numero;
	}

	public void setNumero(int numero) {
		this.numero = numero;
	}

	@Column(name = "cep", length = 10)
	public String getCep() {
		return this.cep;
	}

	public void setCep(String cep) {
		this.cep = cep;
	}

	@Column(name = "complemento", length = 50)
	public String getComplemento() {
		return this.complemento;
	}

	public void setComplemento(String complemento) {
		this.complemento = complemento;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "endereco")
	public Set<EmpresaEntity> getEmpresas() {
		return this.empresas;
	}

	public void setEmpresas(Set<EmpresaEntity> empresas) {
		this.empresas = empresas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "endereco")
	public Set<ClienteEntity> getClientes() {
		return this.clientes;
	}

	public void setClientes(Set<ClienteEntity> clientes) {
		this.clientes = clientes;
	}

	@Override
	public String toString() {
		return "EnderecoEntity [id=" + id + ", logradouro=" + logradouro + ", bairro=" + bairro + ", cidade=" + cidade
				+ ", estado=" + estado + ", numero=" + numero + ", cep=" + cep + ", complemento=" + complemento
				+ ", empresas=" + empresas + ", clientes=" + clientes + "]";
	}
}
