package br.com.fichasordens.entities;
// Generated 03/03/2018 14:18:32 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FichaAtendLanc generated by hbm2java
 */
@Entity
@Table(name = "ficha_atend_lanc", schema = "public")
public class FichaAtendLancEntity implements java.io.Serializable {

	private FichaAtendLancId id;
	private FichaAtendimentoEntity fichaAtendimento;
	private UsuarioEntity usuario;
	private String situacao;
	private Date data;
	private String observacao;
	private Boolean atualSituacao;

	public FichaAtendLancEntity() {
	}

	public FichaAtendLancEntity(FichaAtendLancId id, FichaAtendimentoEntity fichaAtendimento, UsuarioEntity usuario, String situacao,
			Date data, String observacao, Boolean atualSituacao) {
		this.id = id;
		this.fichaAtendimento = fichaAtendimento;
		this.usuario = usuario;
		this.situacao = situacao;
		this.data = data;
		this.observacao = observacao;
		this.atualSituacao = atualSituacao;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "sequencia", column = @Column(name = "sequencia", nullable = false)),
			@AttributeOverride(name = "usuarioId", column = @Column(name = "usuario_id", nullable = false)),
			@AttributeOverride(name = "fichaAtendimentoId", column = @Column(name = "ficha_atendimento_id", nullable = false, precision = 131089, scale = 0)) })
	public FichaAtendLancId getId() {
		return this.id;
	}

	public void setId(FichaAtendLancId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ficha_atendimento_id", nullable = false, insertable = false, updatable = false)
	public FichaAtendimentoEntity getFichaAtendimento() {
		return this.fichaAtendimento;
	}

	public void setFichaAtendimento(FichaAtendimentoEntity fichaAtendimento) {
		this.fichaAtendimento = fichaAtendimento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_id", nullable = false, insertable = false, updatable = false)
	public UsuarioEntity getUsuario() {
		return this.usuario;
	}

	public void setUsuario(UsuarioEntity usuario) {
		this.usuario = usuario;
	}

	@Column(name = "situacao", nullable = false, length = 10)
	public String getSituacao() {
		return this.situacao;
	}

	public void setSituacao(String situacao) {
		this.situacao = situacao;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data", nullable = false, length = 13)
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	@Column(name = "observacao", nullable = false)
	public String getObservacao() {
		return this.observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

	@Column(name = "atual_situacao", nullable = false)
	public Boolean getAtualSituacao() {
		return atualSituacao;
	}

	public void setAtualSituacao(Boolean atualSituacao) {
		this.atualSituacao = atualSituacao;
	}
	
}
