package br.com.fichasordens.entities;
// Generated 03/03/2018 14:18:32 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FichaAtendLancId generated by hbm2java
 */
@Embeddable
public class FichaAtendLancId implements java.io.Serializable {

	private int sequencia;
	private long usuarioId;
	private long fichaAtendimentoId;

	public FichaAtendLancId() {
	}

	public FichaAtendLancId(final int sequencia, final long usuarioId, final long fichaAtendimentoId) {
		this.sequencia = sequencia;
		this.usuarioId = usuarioId;
		this.fichaAtendimentoId = fichaAtendimentoId;
	}

	@Column(name = "sequencia", nullable = false)
	public int getSequencia() {
		return this.sequencia;
	}

	public void setSequencia(int sequencia) {
		this.sequencia = sequencia;
	}

	@Column(name = "usuario_id", nullable = false)
	public long getUsuarioId() {
		return this.usuarioId;
	}

	public void setUsuarioId(final long usuarioId) {
		this.usuarioId = usuarioId;
	}

	@Column(name = "ficha_atendimento_id", nullable = false, precision = 131089, scale = 0)
	public long getFichaAtendimentoId() {
		return this.fichaAtendimentoId;
	}

	public void setFichaAtendimentoId(long fichaAtendimentoId) {
		this.fichaAtendimentoId = fichaAtendimentoId;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + sequencia;
		result = prime * result + (int) (usuarioId ^ (usuarioId >>> 32));
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		FichaAtendLancId other = (FichaAtendLancId) obj;
		if (sequencia != other.sequencia)
			return false;
		if (usuarioId != other.usuarioId)
			return false;
		return true;
	}

}
