package br.com.fichasordens.entities;
// Generated 03/03/2018 14:18:32 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * FichaAtendimento generated by hbm2java
 */
@Entity
@Table(name = "ficha_atendimento", schema = "public")
public class FichaAtendimentoEntity implements java.io.Serializable {

	private long id;
	private ClienteEntity cliente;
	private String tipoServico;
	private Set<PecaServicoFichaEntity> pecaServicoFichas = new HashSet<>(0);
	private Set<FichaAtendLancEntity> fichaAtendLancs = new HashSet<>(0);
	private Set<AtendimentoFichaEntity> atendimentoFichas = new HashSet<>(0);

	public FichaAtendimentoEntity() {
	}

	public FichaAtendimentoEntity(long id, ClienteEntity cliente, String tipoServico) {
		this.id = id;
		this.cliente = cliente;
		this.tipoServico = tipoServico;
	}

	public FichaAtendimentoEntity(long id, ClienteEntity cliente, String tipoServico, Set<PecaServicoFichaEntity> pecaServicoFichas,
			Set<FichaAtendLancEntity> fichaAtendLancs, Set<AtendimentoFichaEntity> atendimentoFichas) {
		this.id = id;
		this.cliente = cliente;
		this.tipoServico = tipoServico;
		this.pecaServicoFichas = pecaServicoFichas;
		this.fichaAtendLancs = fichaAtendLancs;
		this.atendimentoFichas = atendimentoFichas;
	}

	
	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="ficha_sequencia")
	@SequenceGenerator(name="ficha_sequencia", sequenceName="ficha_sequencia", allocationSize=1)
	@Column(name = "id", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cliente_id", nullable = false)
	public ClienteEntity getCliente() {
		return this.cliente;
	}

	public void setCliente(ClienteEntity cliente) {
		this.cliente = cliente;
	}

	@Column(name = "tipo_servico", nullable = false, length = 20)
	public String getTipoServico() {
		return this.tipoServico;
	}

	public void setTipoServico(String tipoServico) {
		this.tipoServico = tipoServico;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fichaAtendimento")
	public Set<PecaServicoFichaEntity> getPecaServicoFichas() {
		return this.pecaServicoFichas;
	}

	public void setPecaServicoFichas(Set<PecaServicoFichaEntity> pecaServicoFichas) {
		this.pecaServicoFichas = pecaServicoFichas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fichaAtendimento")
	public Set<FichaAtendLancEntity> getFichaAtendLancs() {
		return this.fichaAtendLancs;
	}

	public void setFichaAtendLancs(Set<FichaAtendLancEntity> fichaAtendLancs) {
		this.fichaAtendLancs = fichaAtendLancs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fichaAtendimento")
	public Set<AtendimentoFichaEntity> getAtendimentoFichas() {
		return this.atendimentoFichas;
	}

	public void setAtendimentoFichas(Set<AtendimentoFichaEntity> atendimentoFichas) {
		this.atendimentoFichas = atendimentoFichas;
	}

}
