package br.com.fichasordens.entities;
// Generated 03/03/2018 14:18:32 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FichaAtendLancId generated by hbm2java
 */
@Embeddable
public class FichaAtendLancId implements java.io.Serializable {

	private int sequencia;
	private String usuarioId;
	private BigDecimal fichaAtendimentoId;

	public FichaAtendLancId() {
	}

	public FichaAtendLancId(int sequencia, String usuarioId, BigDecimal fichaAtendimentoId) {
		this.sequencia = sequencia;
		this.usuarioId = usuarioId;
		this.fichaAtendimentoId = fichaAtendimentoId;
	}

	@Column(name = "sequencia", nullable = false)
	public int getSequencia() {
		return this.sequencia;
	}

	public void setSequencia(int sequencia) {
		this.sequencia = sequencia;
	}

	@Column(name = "usuario_id", nullable = false)
	public String getUsuarioId() {
		return this.usuarioId;
	}

	public void setUsuarioId(String usuarioId) {
		this.usuarioId = usuarioId;
	}

	@Column(name = "ficha_atendimento_id", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getFichaAtendimentoId() {
		return this.fichaAtendimentoId;
	}

	public void setFichaAtendimentoId(BigDecimal fichaAtendimentoId) {
		this.fichaAtendimentoId = fichaAtendimentoId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FichaAtendLancId))
			return false;
		FichaAtendLancId castOther = (FichaAtendLancId) other;

		return (this.getSequencia() == castOther.getSequencia())
				&& ((this.getUsuarioId() == castOther.getUsuarioId()) || (this.getUsuarioId() != null
						&& castOther.getUsuarioId() != null && this.getUsuarioId().equals(castOther.getUsuarioId())))
				&& ((this.getFichaAtendimentoId() == castOther.getFichaAtendimentoId())
						|| (this.getFichaAtendimentoId() != null && castOther.getFichaAtendimentoId() != null
								&& this.getFichaAtendimentoId().equals(castOther.getFichaAtendimentoId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSequencia();
		result = 37 * result + (getUsuarioId() == null ? 0 : this.getUsuarioId().hashCode());
		result = 37 * result + (getFichaAtendimentoId() == null ? 0 : this.getFichaAtendimentoId().hashCode());
		return result;
	}

}
