package br.com.fichasordens.entities;
// Generated 13/07/2018 23:50:53 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrdemServicoLancId generated by hbm2java
 */
@Embeddable
public class OrdemServicoLancId implements java.io.Serializable {

	private long sequencia;
	private long usuarioId;
	private long ordemServicoId;

	public OrdemServicoLancId() {
	}

	public OrdemServicoLancId(long sequencia, long usuarioId, long ordemServicoId) {
		this.sequencia = sequencia;
		this.usuarioId = usuarioId;
		this.ordemServicoId = ordemServicoId;
	}

	@Column(name = "sequencia", nullable = false, precision = 10, scale = 0)
	public long getSequencia() {
		return this.sequencia;
	}

	public void setSequencia(long sequencia) {
		this.sequencia = sequencia;
	}

	@Column(name = "usuario_id", nullable = false, precision = 10, scale = 0)
	public long getUsuarioId() {
		return this.usuarioId;
	}

	public void setUsuarioId(long usuarioId) {
		this.usuarioId = usuarioId;
	}

	@Column(name = "ordem_servico_id", nullable = false, precision = 10, scale = 0)
	public long getOrdemServicoId() {
		return this.ordemServicoId;
	}

	public void setOrdemServicoId(long ordemServicoId) {
		this.ordemServicoId = ordemServicoId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrdemServicoLancId))
			return false;
		OrdemServicoLancId castOther = (OrdemServicoLancId) other;

		return (this.getSequencia() == castOther.getSequencia()) && (this.getUsuarioId() == castOther.getUsuarioId())
				&& (this.getOrdemServicoId() == castOther.getOrdemServicoId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getSequencia();
		result = 37 * result + (int) this.getUsuarioId();
		result = 37 * result + (int) this.getOrdemServicoId();
		return result;
	}

}
