package br.com.fichasordens.entities;
// Generated 13/07/2018 23:50:53 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrdemServicoLanc generated by hbm2java
 */
@Entity
@Table(name = "ordem_servico_lanc", schema = "public")
public class OrdemServicoLancEntity implements java.io.Serializable {

	private OrdemServicoLancId id;
	private OrdemServicoEntity ordemServico;
	private UsuarioEntity usuario;
	private String situacao;
	private Date data;
	private String observacao;
	private Boolean atualSituacao;

	public OrdemServicoLancEntity() {
	}

	public OrdemServicoLancEntity(OrdemServicoLancId id, OrdemServicoEntity ordemServico, UsuarioEntity usuario, String situacao) {
		this.id = id;
		this.ordemServico = ordemServico;
		this.usuario = usuario;
		this.situacao = situacao;
	}

	public OrdemServicoLancEntity(OrdemServicoLancId id, OrdemServicoEntity ordemServico, UsuarioEntity usuario, String situacao,
			Date data, String observacao, Boolean atualSituacao) {
		this.id = id;
		this.ordemServico = ordemServico;
		this.usuario = usuario;
		this.situacao = situacao;
		this.data = data;
		this.observacao = observacao;
		this.atualSituacao = atualSituacao;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "sequencia", column = @Column(name = "sequencia", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "usuarioId", column = @Column(name = "usuario_id", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "ordemServicoId", column = @Column(name = "ordem_servico_id", nullable = false, precision = 10, scale = 0)) })
	public OrdemServicoLancId getId() {
		return this.id;
	}

	public void setId(OrdemServicoLancId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ordem_servico_id", nullable = false, insertable = false, updatable = false)
	public OrdemServicoEntity getOrdemServico() {
		return this.ordemServico;
	}

	public void setOrdemServico(OrdemServicoEntity ordemServico) {
		this.ordemServico = ordemServico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_id", nullable = false, insertable = false, updatable = false)
	public UsuarioEntity getUsuario() {
		return this.usuario;
	}

	public void setUsuario(UsuarioEntity usuario) {
		this.usuario = usuario;
	}

	@Column(name = "situacao", nullable = false, length = 15)
	public String getSituacao() {
		return this.situacao;
	}

	public void setSituacao(String situacao) {
		this.situacao = situacao;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data", length = 13)
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	@Column(name = "observacao", length = 255)
	public String getObservacao() {
		return this.observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

	@Column(name = "atual_situacao", nullable=false)
	public Boolean getAtualSituacao() {
		return atualSituacao;
	}

	public void setAtualSituacao(Boolean atualSituacao) {
		this.atualSituacao = atualSituacao;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((ordemServico == null) ? 0 : ordemServico.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		OrdemServicoLancEntity other = (OrdemServicoLancEntity) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (ordemServico == null) {
			if (other.ordemServico != null)
				return false;
		} else if (!ordemServico.equals(other.ordemServico))
			return false;
		return true;
	}
	
	
}
