package br.com.fichasordens.entities;
// Generated 03/03/2018 14:18:32 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PecaServicoFicha generated by hbm2java
 */
@Entity
@Table(name = "peca_servico_ficha", schema = "public")
public class PecaServicoFichaEntity implements java.io.Serializable {

	private PecaServicoFichaIdEntity id;
	private FichaAtendimentoEntity fichaAtendimento;
	private String descricao;
	private long quantidade;
	private BigDecimal valor;
	private Date data;

	public PecaServicoFichaEntity() {
	}

	public PecaServicoFichaEntity(PecaServicoFichaIdEntity id, FichaAtendimentoEntity fichaAtendimento, String descricao, long quantidade,
			BigDecimal valor) {
		this.id = id;
		this.fichaAtendimento = fichaAtendimento;
		this.descricao = descricao;
		this.quantidade = quantidade;
		this.valor = valor;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "fichaAtendId", column = @Column(name = "ficha_atend_id", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "sequencia", column = @Column(name = "sequencia", nullable = false, precision = 10, scale = 0)) })
	public PecaServicoFichaIdEntity getId() {
		return this.id;
	}

	public void setId(PecaServicoFichaIdEntity id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ficha_atend_id", nullable = false, insertable = false, updatable = false)
	public FichaAtendimentoEntity getFichaAtendimento() {
		return this.fichaAtendimento;
	}

	public void setFichaAtendimento(FichaAtendimentoEntity fichaAtendimento) {
		this.fichaAtendimento = fichaAtendimento;
	}

	@Column(name = "descricao", nullable = false, length = 150)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "quantidade", precision = 3, scale = 0, nullable = false)
	public long getQuantidade() {
		return this.quantidade;
	}

	public void setQuantidade(long quantidade) {
		this.quantidade = quantidade;
	}

	@Column(name = "valor", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "data", length = 13, nullable = false)
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

}
