package br.com.fichasordens.entities;
// Generated 03/03/2018 14:18:32 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PecaServicoOrdem generated by hbm2java
 */
@Entity
@Table(name = "peca_servico_ordem", schema = "public")
public class PecaServicoOrdemEntity implements java.io.Serializable {

	private PecaServicoOrdemEntityId id;
	private OrdemServicoEntity ordemServico;
	private String descricao;
	private Long quantidade;
	private BigDecimal valor;
	private Date data;

	public PecaServicoOrdemEntity() {
	}

	public PecaServicoOrdemEntity(PecaServicoOrdemEntityId id) {
		this.id = id;
	}

	public PecaServicoOrdemEntity(PecaServicoOrdemEntityId id, Long quantidade, BigDecimal valor) {
		this.id = id;
		this.quantidade = quantidade;
		this.valor = valor;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "sequencia", column = @Column(name = "sequencia", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "ordemServicoId", column = @Column(name = "ordem_servico_id", nullable = false, precision = 10, scale = 0))
			})
	public PecaServicoOrdemEntityId getId() {
		return this.id;
	}

	public void setId(PecaServicoOrdemEntityId id) {
		this.id = id;
	}

	@Column(name = "quantidade", precision = 3, scale = 0)
	public Long getQuantidade() {
		return quantidade;
	}

	public void setQuantidade(Long quantidade) {
		this.quantidade = quantidade;
	}

	@Column(name = "valor", precision = 8)
	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	@Column(name = "descricao", nullable = false, length = 150)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ordem_servico_id", nullable = false, insertable = false, updatable = false)
	public OrdemServicoEntity getOrdemServico() {
		return this.ordemServico;
	}

	public void setOrdemServico(OrdemServicoEntity ordemServico) {
		this.ordemServico = ordemServico;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "data", length = 13, nullable = false)
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}
}
