package br.com.fichasordens.entities;
// Generated 03/03/2018 14:18:32 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PecaServicoFichaId generated by hbm2java
 */
@Embeddable
public class PecaServicoFichaIdEntity implements java.io.Serializable {

	private long fichaAtendId;
	private long sequencia;

	public PecaServicoFichaIdEntity() {
	}

	public PecaServicoFichaIdEntity(long fichaAtendId, long sequencia) {
		this.fichaAtendId = fichaAtendId;
		this.sequencia = sequencia;
	}

	@Column(name = "ficha_atend_id", nullable = false, precision = 10, scale = 0)
	public long getFichaAtendId() {
		return this.fichaAtendId;
	}

	public void setFichaAtendId(long fichaAtendId) {
		this.fichaAtendId = fichaAtendId;
	}

	@Column(name = "sequencia", nullable = false, precision = 10, scale = 0)
	public long getSequencia() {
		return this.sequencia;
	}

	public void setSequencia(long sequencia) {
		this.sequencia = sequencia;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PecaServicoFichaIdEntity))
			return false;
		PecaServicoFichaIdEntity castOther = (PecaServicoFichaIdEntity) other;

		return (this.getFichaAtendId() == castOther.getFichaAtendId())
				&& (this.getSequencia() == castOther.getSequencia());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getFichaAtendId();
		result = 37 * result + (int) this.getSequencia();
		return result;
	}

}
