package br.com.fichasordens.entities;
// Generated 03/03/2018 14:18:32 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PecaServicoOrdemId generated by hbm2java
 */
@Embeddable
public class PecaServicoOrdemEntityId implements java.io.Serializable {

	private long sequencia;
	private long ordemServicoId;

	public PecaServicoOrdemEntityId() {
	}

	public PecaServicoOrdemEntityId(long sequencia, long ordemServicoId) {
		this.sequencia = sequencia;
		this.ordemServicoId = ordemServicoId;
	}

	@Column(name = "sequencia", nullable = false, precision = 10, scale = 0)
	public long getSequencia() {
		return this.sequencia;
	}

	public void setSequencia(long sequencia) {
		this.sequencia = sequencia;
	}

	@Column(name = "ordem_servico_id", nullable = false, precision = 10, scale = 0)
	public long getOrdemServicoId() {
		return this.ordemServicoId;
	}

	public void setOrdemServicoId(long ordemServicoId) {
		this.ordemServicoId = ordemServicoId;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + (int) (ordemServicoId ^ (ordemServicoId >>> 32));
		result = prime * result + (int) (sequencia ^ (sequencia >>> 32));
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PecaServicoOrdemEntityId other = (PecaServicoOrdemEntityId) obj;
		if (ordemServicoId != other.ordemServicoId)
			return false;
		if (sequencia != other.sequencia)
			return false;
		return true;
	}

}
