package br.com.fichasordens.entities;
// Generated 03/03/2018 14:18:32 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PecaServicoFicha generated by hbm2java
 */
@Entity
@Table(name = "peca_servico_ficha", schema = "public")
public class PecaServicoFicha implements java.io.Serializable {

	private PecaServicoFichaId id;
	private FichaAtendimento fichaAtendimento;
	private String descricao;
	private int quantidade;
	private BigDecimal valor;

	public PecaServicoFicha() {
	}

	public PecaServicoFicha(PecaServicoFichaId id, FichaAtendimento fichaAtendimento, String descricao, int quantidade,
			BigDecimal valor) {
		this.id = id;
		this.fichaAtendimento = fichaAtendimento;
		this.descricao = descricao;
		this.quantidade = quantidade;
		this.valor = valor;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "fichaAtendId", column = @Column(name = "ficha_atend_id", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "sequencia", column = @Column(name = "sequencia", nullable = false, precision = 10, scale = 0)) })
	public PecaServicoFichaId getId() {
		return this.id;
	}

	public void setId(PecaServicoFichaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ficha_atend_id", nullable = false, insertable = false, updatable = false)
	public FichaAtendimento getFichaAtendimento() {
		return this.fichaAtendimento;
	}

	public void setFichaAtendimento(FichaAtendimento fichaAtendimento) {
		this.fichaAtendimento = fichaAtendimento;
	}

	@Column(name = "descricao", nullable = false, length = 150)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "quantidade", nullable = false)
	public int getQuantidade() {
		return this.quantidade;
	}

	public void setQuantidade(int quantidade) {
		this.quantidade = quantidade;
	}

	@Column(name = "valor", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

}
