package br.com.fichasordens;
// Generated 03/03/2018 14:18:32 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AtendimentoFichaId generated by hbm2java
 */
@Embeddable
public class AtendimentoFichaId implements java.io.Serializable {

	private int sequencia;
	private long fichaAtendimentoId;

	public AtendimentoFichaId() {
	}

	public AtendimentoFichaId(int sequencia, long fichaAtendimentoId) {
		this.sequencia = sequencia;
		this.fichaAtendimentoId = fichaAtendimentoId;
	}

	@Column(name = "sequencia", nullable = false)
	public int getSequencia() {
		return this.sequencia;
	}

	public void setSequencia(int sequencia) {
		this.sequencia = sequencia;
	}

	@Column(name = "ficha_atendimento_id", nullable = false, precision = 10, scale = 0)
	public long getFichaAtendimentoId() {
		return this.fichaAtendimentoId;
	}

	public void setFichaAtendimentoId(long fichaAtendimentoId) {
		this.fichaAtendimentoId = fichaAtendimentoId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AtendimentoFichaId))
			return false;
		AtendimentoFichaId castOther = (AtendimentoFichaId) other;

		return (this.getSequencia() == castOther.getSequencia())
				&& (this.getFichaAtendimentoId() == castOther.getFichaAtendimentoId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSequencia();
		result = 37 * result + (int) this.getFichaAtendimentoId();
		return result;
	}

}
