package br.com.fichasordens;
// Generated 03/03/2018 14:18:32 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FichaAtendimento generated by hbm2java
 */
@Entity
@Table(name = "ficha_atendimento", schema = "public")
public class FichaAtendimento implements java.io.Serializable {

	private long id;
	private Cliente cliente;
	private String tipoServico;
	private Set<PecaServicoFicha> pecaServicoFichas = new HashSet<PecaServicoFicha>(0);
	private Set<FichaAtendLanc> fichaAtendLancs = new HashSet<FichaAtendLanc>(0);
	private Set<AtendimentoFicha> atendimentoFichas = new HashSet<AtendimentoFicha>(0);

	public FichaAtendimento() {
	}

	public FichaAtendimento(long id, Cliente cliente, String tipoServico) {
		this.id = id;
		this.cliente = cliente;
		this.tipoServico = tipoServico;
	}

	public FichaAtendimento(long id, Cliente cliente, String tipoServico, Set<PecaServicoFicha> pecaServicoFichas,
			Set<FichaAtendLanc> fichaAtendLancs, Set<AtendimentoFicha> atendimentoFichas) {
		this.id = id;
		this.cliente = cliente;
		this.tipoServico = tipoServico;
		this.pecaServicoFichas = pecaServicoFichas;
		this.fichaAtendLancs = fichaAtendLancs;
		this.atendimentoFichas = atendimentoFichas;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cliente_id", nullable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@Column(name = "tipo_servico", nullable = false, length = 20)
	public String getTipoServico() {
		return this.tipoServico;
	}

	public void setTipoServico(String tipoServico) {
		this.tipoServico = tipoServico;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fichaAtendimento")
	public Set<PecaServicoFicha> getPecaServicoFichas() {
		return this.pecaServicoFichas;
	}

	public void setPecaServicoFichas(Set<PecaServicoFicha> pecaServicoFichas) {
		this.pecaServicoFichas = pecaServicoFichas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fichaAtendimento")
	public Set<FichaAtendLanc> getFichaAtendLancs() {
		return this.fichaAtendLancs;
	}

	public void setFichaAtendLancs(Set<FichaAtendLanc> fichaAtendLancs) {
		this.fichaAtendLancs = fichaAtendLancs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fichaAtendimento")
	public Set<AtendimentoFicha> getAtendimentoFichas() {
		return this.atendimentoFichas;
	}

	public void setAtendimentoFichas(Set<AtendimentoFicha> atendimentoFichas) {
		this.atendimentoFichas = atendimentoFichas;
	}

}
