package br.com.fichasordens;
// Generated 03/03/2018 14:18:32 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Parametro generated by hbm2java
 */
@Entity
@Table(name = "parametro", schema = "public")
public class Parametro implements java.io.Serializable {

	private byte id;
	private String descricao;
	private BigDecimal valor;

	public Parametro() {
	}

	public Parametro(byte id) {
		this.id = id;
	}

	public Parametro(byte id, String descricao, BigDecimal valor) {
		this.id = id;
		this.descricao = descricao;
		this.valor = valor;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, precision = 2, scale = 0)
	public byte getId() {
		return this.id;
	}

	public void setId(byte id) {
		this.id = id;
	}

	@Column(name = "descricao", length = 15)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "valor", precision = 4)
	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

}
