package br.com.fichasordens;
// Generated 03/03/2018 14:18:32 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PecaServicoOrdemId generated by hbm2java
 */
@Embeddable
public class PecaServicoOrdemId implements java.io.Serializable {

	private long sequencia;
	private long ordemServicoId;
	private String descricao;

	public PecaServicoOrdemId() {
	}

	public PecaServicoOrdemId(long sequencia, long ordemServicoId, String descricao) {
		this.sequencia = sequencia;
		this.ordemServicoId = ordemServicoId;
		this.descricao = descricao;
	}

	@Column(name = "sequencia", nullable = false, precision = 10, scale = 0)
	public long getSequencia() {
		return this.sequencia;
	}

	public void setSequencia(long sequencia) {
		this.sequencia = sequencia;
	}

	@Column(name = "ordem_servico_id", nullable = false, precision = 10, scale = 0)
	public long getOrdemServicoId() {
		return this.ordemServicoId;
	}

	public void setOrdemServicoId(long ordemServicoId) {
		this.ordemServicoId = ordemServicoId;
	}

	@Column(name = "descricao", nullable = false, length = 150)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PecaServicoOrdemId))
			return false;
		PecaServicoOrdemId castOther = (PecaServicoOrdemId) other;

		return (this.getSequencia() == castOther.getSequencia())
				&& (this.getOrdemServicoId() == castOther.getOrdemServicoId())
				&& ((this.getDescricao() == castOther.getDescricao()) || (this.getDescricao() != null
						&& castOther.getDescricao() != null && this.getDescricao().equals(castOther.getDescricao())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getSequencia();
		result = 37 * result + (int) this.getOrdemServicoId();
		result = 37 * result + (getDescricao() == null ? 0 : this.getDescricao().hashCode());
		return result;
	}

}
