package br.com.fichasordens;
// Generated 03/03/2018 14:18:32 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PecaServicoOrdem generated by hbm2java
 */
@Entity
@Table(name = "peca_servico_ordem", schema = "public")
public class PecaServicoOrdem implements java.io.Serializable {

	private PecaServicoOrdemId id;
	private Short quantidade;
	private BigDecimal valor;

	public PecaServicoOrdem() {
	}

	public PecaServicoOrdem(PecaServicoOrdemId id) {
		this.id = id;
	}

	public PecaServicoOrdem(PecaServicoOrdemId id, Short quantidade, BigDecimal valor) {
		this.id = id;
		this.quantidade = quantidade;
		this.valor = valor;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "sequencia", column = @Column(name = "sequencia", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "ordemServicoId", column = @Column(name = "ordem_servico_id", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "descricao", column = @Column(name = "descricao", nullable = false, length = 150)) })
	public PecaServicoOrdemId getId() {
		return this.id;
	}

	public void setId(PecaServicoOrdemId id) {
		this.id = id;
	}

	@Column(name = "quantidade", precision = 3, scale = 0)
	public Short getQuantidade() {
		return this.quantidade;
	}

	public void setQuantidade(Short quantidade) {
		this.quantidade = quantidade;
	}

	@Column(name = "valor", precision = 8)
	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

}
