package br.com.fichasordens;
// Generated 03/03/2018 14:18:32 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", schema = "public")
public class Usuario implements java.io.Serializable {

	private String usuario;
	private String nome;
	private String senha;
	private Date dataCad;
	private int situacao;
	private Set<FichaAtendLanc> fichaAtendLancs = new HashSet<FichaAtendLanc>(0);

	public Usuario() {
	}

	public Usuario(String usuario, String nome, String senha, Date dataCad, int situacao) {
		this.usuario = usuario;
		this.nome = nome;
		this.senha = senha;
		this.dataCad = dataCad;
		this.situacao = situacao;
	}

	public Usuario(String usuario, String nome, String senha, Date dataCad, int situacao,
			Set<FichaAtendLanc> fichaAtendLancs) {
		this.usuario = usuario;
		this.nome = nome;
		this.senha = senha;
		this.dataCad = dataCad;
		this.situacao = situacao;
		this.fichaAtendLancs = fichaAtendLancs;
	}

	@Id
	@Column(name = "usuario", unique = true, nullable = false, length = 10)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "nome", nullable = false, length = 50)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "senha", nullable = false, length = 8)
	public String getSenha() {
		return this.senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_cad", nullable = false, length = 13)
	public Date getDataCad() {
		return this.dataCad;
	}

	public void setDataCad(Date dataCad) {
		this.dataCad = dataCad;
	}

	@Column(name = "situacao", nullable = false)
	public int getSituacao() {
		return this.situacao;
	}

	public void setSituacao(int situacao) {
		this.situacao = situacao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<FichaAtendLanc> getFichaAtendLancs() {
		return this.fichaAtendLancs;
	}

	public void setFichaAtendLancs(Set<FichaAtendLanc> fichaAtendLancs) {
		this.fichaAtendLancs = fichaAtendLancs;
	}

	@Override
	public String toString() {
		return "Usuario [usuario=" + usuario + ", nome=" + nome + ", senha=" + senha + ", dataCad=" + dataCad
				+ ", situacao=" + situacao + ", fichaAtendLancs=" + fichaAtendLancs + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((usuario == null) ? 0 : usuario.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Usuario other = (Usuario) obj;
		if (usuario == null) {
			if (other.usuario != null)
				return false;
		} else if (!usuario.equals(other.usuario))
			return false;
		return true;
	}
}